version: "3"

services:
  minio:
    image: minio/minio:latest
    entrypoint: "/bin/sh"
    command: -c "
      mkdir -p /data/.minio.sys/buckets;
      /usr/bin/docker-entrypoint.sh minio server /data"
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: AKIA_MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: minio_secret_key
  createbuckets:
    depends_on: [minio]
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 AKIA_MINIO_ACCESS_KEY minio_secret_key) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/bench-magiconion-s3-bucket-5c7e45b || true
      /usr/bin/mc policy set download myminio/bench-magiconion-s3-bucket-5c7e45b
      exit 0;
      "
